version: '3.8'

services:
  backend:
    build:
      context: ./backend
      args:
        - --no-cache
    ports:
      - "8000:80"
    networks:
      - app-network
    volumes:
      - .env:/app/.env
      - ./data:/app/data
      - ./workflow_artifacts:/app/workflow_artifacts
      - ~/.azure:/root/.azure

  frontend:
    build:
      context: ./frontend
      args:
        - --no-cache
    ports:
      - "8501:8501"
    networks:
      - app-network

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.16.0
    ports:
      - "5000:5000"
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - ./mlruns:/mlflow/mlruns
      - ./.env:/app/.env
#    environment:
#      MLFLOW_TRACKING_URI: "http://0.0.0.0:5000"
#      MLFLOW_BACKEND_STORE_URI: "sqlite:///mlflow.db"
#      MLFLOW_DEFAULT_ARTIFACT_ROOT: "/mlflow/mlruns"
    command: >
      mlflow server --port 5000
      --backend-store-uri sqlite:///mlruns.db 
      --default-artifact-root ./mlruns
      --host 0.0.0.0

networks:
  app-network:
