version: '3.8'

services:
  backend:
    build:
      context: ./backend
      args:
        - --no-cache
    ports:
      - "8000:80"
    networks:
      - app-network
    volumes:
      - .env:/app/.env
      - ./data:/app/data
      - ./workflow_artifacts:/app/workflow_artifacts
      - ~/.azure:/root/.azure

  frontend:
    build:
      context: ./frontend
      args:
        - --no-cache
    ports:
      - "8501:8501"
    networks:
      - app-network

  mlflow:
    image: mlflow/mlflow:latest
    ports:
      - "5000:5000"
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - ./mlruns:/mlflow/mlruns
      - ./.env:/app/.env
    environment:
      MLFLOW_TRACKING_URI: "http://0.0.0.0:5000"
      MLFLOW_BACKEND_STORE_URI: "sqlite:///mlflow.db"
      MLFLOW_DEFAULT_ARTIFACT_ROOT: "/mlflow/mlruns"

networks:
  app-network:
